### PR TITLE
Packaging with setuptools

### PR DESCRIPTION
**Pull request by tesujimath**
This PR fixes a few bugs, but is mainly about packaging.  There's now a setuptools script, to enable this to be built as a pip package.

Note that one consequence of this change is that the code has been modified to work as a package, which means to run it in development mode (i.e. in place), it is necessary to set PATH and PYTHONPATH, as is now done by the `run_dev_dbcan` wrapper script.

When you have merged this, please tag a release version.  I recommend using [SemVer](https://semver.org/), suggest starting with say 0.5.0, since this package has been around for a while.

Then you can build and upload a PyPI package, like this, say:
```
$ python setup.py sdist
$ python setup.py bdist_wheel
$ twine upload dist/*0.5.0*
```

This gives users the very much more comfortable experience of installing this via pip, and having all scripts on the path, e.g.
```
$ pip install dbcan
```

For now, I have made an experimental pip package on the TestPyPI channel, which you can install into a virtualenv like this:
```
$ mkdir -p ~/virtualenvs
$ python3 -m venv ~/virtualenvs/dbcan
$ source ~/virtualenvs/dbcan/bin/activate

(dbcan) $ pip install natsort
(dbcan) $ pip install --index-url https://test.pypi.org/simple/ dbcan
```

(Note that it is necessary to install the natsort dependency separately only while dbcan is on the TestPyPI channel.)

Once this PR is merged, I can follow-up with bioconda packaging.  For now, you can install all dependencies except signalp from bioconda, like this:
```
$ conda create -n dbcan diamond hmmer prodigal fraggenescan
$ conda activate dbcan
```

### CODE REVIEW

**Comment by linnabrown** [comment]
Thanks a lot.
What's more, we need to downgrade hmmer version because HMMER 3.2 will detect the repeat ACESS number, but HMMER 3.1.2b(The version we use) will not.
so,  I think the command should add **version number** like this:
```
conda create -n run_dbcan diamond hmmer=3.1b2 prodigal fraggenescan
source activate run_dbcan
```

**Comment by tesujimath** [comment]
Yes, the conda command which specifies the version of hmmer is better

**Comment by linnabrown** [comment]
Thank you so much. I have revised some little problem and upload it on PyPI

**Comment by linnabrown** [comment]
Hi tesuiji,

Could you give me some suggestion about https://github.com/linnabrown/run_dbcan/blob/master/meta.yaml

It failed to pass the pull request. And says some format of meta.yaml does not conform the requirements.

Thanks a lot!

**Pull request merged**
